version: "3.9"

services:
  postgresql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
