version: "3"

services:
  postgresql:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=mydatabase
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
